"""initial schema

Revision ID: ce5ea2e7f589
Revises: 
Create Date: 2026-04-15 20:35:53.151004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5ea2e7f589'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routine_steps', 'points_value',
               existing_type=sa.INTEGER(),
               comment='Points awarded on completion',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routine_steps', 'points_value',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Points awarded on completion',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
